/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as Google9e338cbf9702c676DothtmlRouteImport } from './routes/google9e338cbf9702c676[.]html'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExchangesRouteImport } from './routes/exchanges'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminWatermarkRouteImport } from './routes/admin-watermark'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as PneuProductIdRouteImport } from './routes/pneu.$productId'
import { Route as TipoAroChar123aroChar125RouteImport } from './routes/$tipo.aro-{$aro}'
import { Route as ApiPublicSitemapRouteImport } from './routes/api/public/sitemap'
import { Route as ApiPublicInmetroBackfillRouteImport } from './routes/api/public/inmetro-backfill'
import { Route as ApiPublicGoogleShoppingRouteImport } from './routes/api/public/google-shopping'
import { Route as ApiPublicFreepayWebhookRouteImport } from './routes/api/public/freepay-webhook'
import { Route as ApiPublicBlackoutWebhookRouteImport } from './routes/api/public/blackout-webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const Google9e338cbf9702c676DothtmlRoute =
  Google9e338cbf9702c676DothtmlRouteImport.update({
    id: '/google9e338cbf9702c676.html',
    path: '/google9e338cbf9702c676.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangesRoute = ExchangesRouteImport.update({
  id: '/exchanges',
  path: '/exchanges',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWatermarkRoute = AdminWatermarkRouteImport.update({
  id: '/admin-watermark',
  path: '/admin-watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PneuProductIdRoute = PneuProductIdRouteImport.update({
  id: '/pneu/$productId',
  path: '/pneu/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const TipoAroChar123aroChar125Route =
  TipoAroChar123aroChar125RouteImport.update({
    id: '/$tipo/aro-{$aro}',
    path: '/$tipo/aro-{$aro}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInmetroBackfillRoute =
  ApiPublicInmetroBackfillRouteImport.update({
    id: '/api/public/inmetro-backfill',
    path: '/api/public/inmetro-backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleShoppingRoute = ApiPublicGoogleShoppingRouteImport.update({
  id: '/api/public/google-shopping',
  path: '/api/public/google-shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFreepayWebhookRoute = ApiPublicFreepayWebhookRouteImport.update({
  id: '/api/public/freepay-webhook',
  path: '/api/public/freepay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBlackoutWebhookRoute =
  ApiPublicBlackoutWebhookRouteImport.update({
    id: '/api/public/blackout-webhook',
    path: '/api/public/blackout-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-watermark': typeof AdminWatermarkRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/exchanges': typeof ExchangesRoute
  '/faq': typeof FaqRoute
  '/google9e338cbf9702c676.html': typeof Google9e338cbf9702c676DothtmlRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/$tipo/aro-{$aro}': typeof TipoAroChar123aroChar125Route
  '/pneu/$productId': typeof PneuProductIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/api/public/blackout-webhook': typeof ApiPublicBlackoutWebhookRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/google-shopping': typeof ApiPublicGoogleShoppingRoute
  '/api/public/inmetro-backfill': typeof ApiPublicInmetroBackfillRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-watermark': typeof AdminWatermarkRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/exchanges': typeof ExchangesRoute
  '/faq': typeof FaqRoute
  '/google9e338cbf9702c676.html': typeof Google9e338cbf9702c676DothtmlRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/$tipo/aro-{$aro}': typeof TipoAroChar123aroChar125Route
  '/pneu/$productId': typeof PneuProductIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products': typeof ProductsIndexRoute
  '/api/public/blackout-webhook': typeof ApiPublicBlackoutWebhookRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/google-shopping': typeof ApiPublicGoogleShoppingRoute
  '/api/public/inmetro-backfill': typeof ApiPublicInmetroBackfillRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-watermark': typeof AdminWatermarkRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/exchanges': typeof ExchangesRoute
  '/faq': typeof FaqRoute
  '/google9e338cbf9702c676.html': typeof Google9e338cbf9702c676DothtmlRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/$tipo/aro-{$aro}': typeof TipoAroChar123aroChar125Route
  '/pneu/$productId': typeof PneuProductIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/api/public/blackout-webhook': typeof ApiPublicBlackoutWebhookRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/google-shopping': typeof ApiPublicGoogleShoppingRoute
  '/api/public/inmetro-backfill': typeof ApiPublicInmetroBackfillRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-watermark'
    | '/checkout'
    | '/contact'
    | '/exchanges'
    | '/faq'
    | '/google9e338cbf9702c676.html'
    | '/payment-methods'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/terms'
    | '/$tipo/aro-{$aro}'
    | '/pneu/$productId'
    | '/products/$productId'
    | '/products/'
    | '/api/public/blackout-webhook'
    | '/api/public/freepay-webhook'
    | '/api/public/google-shopping'
    | '/api/public/inmetro-backfill'
    | '/api/public/sitemap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-watermark'
    | '/checkout'
    | '/contact'
    | '/exchanges'
    | '/faq'
    | '/google9e338cbf9702c676.html'
    | '/payment-methods'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/terms'
    | '/$tipo/aro-{$aro}'
    | '/pneu/$productId'
    | '/products/$productId'
    | '/products'
    | '/api/public/blackout-webhook'
    | '/api/public/freepay-webhook'
    | '/api/public/google-shopping'
    | '/api/public/inmetro-backfill'
    | '/api/public/sitemap'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-watermark'
    | '/checkout'
    | '/contact'
    | '/exchanges'
    | '/faq'
    | '/google9e338cbf9702c676.html'
    | '/payment-methods'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/terms'
    | '/$tipo/aro-{$aro}'
    | '/pneu/$productId'
    | '/products/$productId'
    | '/products/'
    | '/api/public/blackout-webhook'
    | '/api/public/freepay-webhook'
    | '/api/public/google-shopping'
    | '/api/public/inmetro-backfill'
    | '/api/public/sitemap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AdminWatermarkRoute: typeof AdminWatermarkRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ExchangesRoute: typeof ExchangesRoute
  FaqRoute: typeof FaqRoute
  Google9e338cbf9702c676DothtmlRoute: typeof Google9e338cbf9702c676DothtmlRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsRoute: typeof TermsRoute
  TipoAroChar123aroChar125Route: typeof TipoAroChar123aroChar125Route
  PneuProductIdRoute: typeof PneuProductIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiPublicBlackoutWebhookRoute: typeof ApiPublicBlackoutWebhookRoute
  ApiPublicFreepayWebhookRoute: typeof ApiPublicFreepayWebhookRoute
  ApiPublicGoogleShoppingRoute: typeof ApiPublicGoogleShoppingRoute
  ApiPublicInmetroBackfillRoute: typeof ApiPublicInmetroBackfillRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google9e338cbf9702c676.html': {
      id: '/google9e338cbf9702c676.html'
      path: '/google9e338cbf9702c676.html'
      fullPath: '/google9e338cbf9702c676.html'
      preLoaderRoute: typeof Google9e338cbf9702c676DothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchanges': {
      id: '/exchanges'
      path: '/exchanges'
      fullPath: '/exchanges'
      preLoaderRoute: typeof ExchangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-watermark': {
      id: '/admin-watermark'
      path: '/admin-watermark'
      fullPath: '/admin-watermark'
      preLoaderRoute: typeof AdminWatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pneu/$productId': {
      id: '/pneu/$productId'
      path: '/pneu/$productId'
      fullPath: '/pneu/$productId'
      preLoaderRoute: typeof PneuProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tipo/aro-{$aro}': {
      id: '/$tipo/aro-{$aro}'
      path: '/$tipo/aro-{$aro}'
      fullPath: '/$tipo/aro-{$aro}'
      preLoaderRoute: typeof TipoAroChar123aroChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inmetro-backfill': {
      id: '/api/public/inmetro-backfill'
      path: '/api/public/inmetro-backfill'
      fullPath: '/api/public/inmetro-backfill'
      preLoaderRoute: typeof ApiPublicInmetroBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-shopping': {
      id: '/api/public/google-shopping'
      path: '/api/public/google-shopping'
      fullPath: '/api/public/google-shopping'
      preLoaderRoute: typeof ApiPublicGoogleShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/freepay-webhook': {
      id: '/api/public/freepay-webhook'
      path: '/api/public/freepay-webhook'
      fullPath: '/api/public/freepay-webhook'
      preLoaderRoute: typeof ApiPublicFreepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blackout-webhook': {
      id: '/api/public/blackout-webhook'
      path: '/api/public/blackout-webhook'
      fullPath: '/api/public/blackout-webhook'
      preLoaderRoute: typeof ApiPublicBlackoutWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AdminWatermarkRoute: AdminWatermarkRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ExchangesRoute: ExchangesRoute,
  FaqRoute: FaqRoute,
  Google9e338cbf9702c676DothtmlRoute: Google9e338cbf9702c676DothtmlRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsRoute: TermsRoute,
  TipoAroChar123aroChar125Route: TipoAroChar123aroChar125Route,
  PneuProductIdRoute: PneuProductIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiPublicBlackoutWebhookRoute: ApiPublicBlackoutWebhookRoute,
  ApiPublicFreepayWebhookRoute: ApiPublicFreepayWebhookRoute,
  ApiPublicGoogleShoppingRoute: ApiPublicGoogleShoppingRoute,
  ApiPublicInmetroBackfillRoute: ApiPublicInmetroBackfillRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
